version: "2.1"

services:
  # BackstopJS
  backstop:
    hostname: backstop
    image: docksal/backstopjs
    volumes:
      - ${PROJECT_ROOT}/tests/backstop:/src
    # Keep the container running
    entrypoint: "top -b"

  # Behat
  behat:
    hostname: behat
    image: docksal/behat
    volumes:
      - ${PROJECT_ROOT}/tests/behat:/src
    # Keep the container running
    entrypoint: "top -b"

  # Selenium
  browser:
    hostname: browser
    # Pick/uncomment one
    # Pin selenium image to an older version
    # See https://github.com/docksal/docksal/issues/1096#issuecomment-543316840
    image: selenium/standalone-chrome-debug:3.141.59
    #image: selenium/standalone-firefox-debug:3.141.59
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /dev/shm:/dev/shm
    # VNC port for debugging
    # Host: <your-docker-host>:5900 (e.g, localhost:5900, 192.168.64.100:5900)
    # Password: secret
    ports:
      - 5900:5900

  # Web (reports)
  web:
    hostname: web
    image: httpd:alpine
    volumes:
      - ${PROJECT_ROOT}/tests:/usr/local/apache2/htdocs/tests
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
