#!/usr/bin/env bash

## Run BackstopJS
##
## Usage: fin backstop

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Run backstop
BACKSTOPJS="docker exec $(docker-compose ps -q backstop) backstop"

$BACKSTOPJS "$@"
