#!/usr/bin/env bash

## Run an example BackstopJS configuration
##
## Usage: fin backstop-example

# Abort if anything fails
set -e

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Symlink reports html directory
cd $PROJECT_ROOT
if [[ ! -d "docroot/tests/backstop" ]]; then
	# Create symlink inside the cli container (this will not work if executed on Windows directly)
	fin exec "mkdir -p docroot/tests;
	ln -sf ../../tests/backstop docroot/tests/backstop;"
fi

# Run backstop
fin docker-compose run --rm backstop reference --configPath=backstop-example.json
fin docker-compose run --rm backstop test --configPath=backstop-example.json

# HTML report link
echo
echo -e "${green}To view HTML report open: ${NC}"
echo -e "http://qa.docksal/tests/backstop/data/example/reports/html/"
