#!/usr/bin/env bash

## Run Behat v3.x
##
## Usage: fin behat3


# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Run Behat
BEHAT="docker exec $(docker-compose ps -q behat) behat"

$BEHAT "$@"
