#!/usr/bin/env bash

## Run an example Behat configuration
##
## Usage: fin behat-example

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Run Behat
BEHAT="docker exec $(docker-compose ps -q behat) behat"
 
$BEHAT --colors --format=pretty --out=std --format=junit --out=reports/junit --format=html --out=reports/html features/blackbox.feature

# HTML report link
echo
echo -e "${green}To view HTML report open: ${NC}"
echo -e "http://qa.docksal/tests/behat/reports/html/"
