#!/usr/bin/env bash

## Initialize Docksal powered QA stack
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# $PROJECT_ROOT is passed down from fin to any custom command
DOCROOT='docroot'
# Set to the appropriate site domain
SITE_DOMAIN='qa.docksal'

#-------------------------- END: Settings --------------------------------


#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

if_failed ()
{
	if [ ! $? -eq 0 ]; then
		if [[ "$1" == "" ]]; then msg="an error occurred"; else msg="$1"; fi
		echo-red "$msg";
		exit 1;
	fi
}

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
    local source="$1"
    local dest="$2"

    if [[ ! -f $dest ]]; then
        echo "Copying ${dest}..."
        cp $source $dest
    else
        echo-yellow "${dest} already in place."
    fi
}

#-------------------------- END: Helper functions --------------------------------


#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
    # Copy from settings templates
    copy_settings_file "${PROJECT_ROOT}/.docksal/docksal-local.yml" "${PROJECT_ROOT}/docker-compose.yml"
    copy_settings_file "${PROJECT_ROOT}/tests/behat/behat.yml.dist" "${PROJECT_ROOT}/tests/behat/behat.yml"
}

# Initialize Behat suite
init_behat ()
{
	cd $PROJECT_ROOT/tests/behat
	fin exec "composer install --prefer-dist --no-interaction"
}

#-------------------------- END: Functions --------------------------------


#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

echo -e "${green_bg} Step 1 ${NC}${green} Initializing local stack configuration...${NC}"
init_settings


echo -e "${green_bg} Step 2 ${NC}${green} Starting services...${NC}"
if [[ $DOCKER_RUNNING == "true" ]]; then
	fin reset -f
else
	fin up
fi

echo -e "${green_bg} Step 3 ${NC}${green} Initializing test suites...${NC}"
init_behat

if is_windows; then
	echo-green "Add ${SITE_DOMAIN} to your hosts file (/etc/hosts), e.g.:"
	echo-green "192.168.10.10  ${SITE_DOMAIN}"
	echo
fi

echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${SITE_DOMAIN}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
